### ISSUE TITLE
Criar tela Interna Animais

### ISSUE THREAD

**Issue by lucasgmagalhaes** [lucasgmagalhaes/Arca#23]
![image](https://user-images.githubusercontent.com/19666463/66703660-4cb65c00-eceb-11e9-8811-90d0a199fad0.png)

**Comment by fabianomaximiano** [comment]
boa tarde, me interessei pelo projeto e gostaria de  contribuir com algo no projeto.
Posso montar esta tela com bootstrap?
posso lhe enviar uma ideia com visual de como ficara resultado final e lhe enviar para provar, assim fica mais facil de nos entender.  podemos fazer desta forma?

**Comment by lucasgmagalhaes** [comment]
Fala @fabianomaximiano. Muito obrigado pelo interesse, mas o projeto é um trabalho de faculdade. Então infelizmente não podemos aceitar ajuda externa para o desenvolvimento do mesmo.
